### ISSUE TITLE
Feature Request: Server info improvement

### ISSUE THREAD

**Issue by LadyNanuia** [ksandin/racp#195]
Requesting a feature that exists in Flux CP where you can see total zeny, guilds, accounts and characters created on the server along with class distribution in Server information
![image](https://github.com/ksandin/racp/assets/54687998/aa77ab7a-4676-41b6-9ba7-efabfa7a12ef)

as shown in the photo

**Comment by ksandin** [comment]
What do you use it for?

**Comment by LadyNanuia** [comment]
> What do you use it for? And should not your previous request be enough: #185 ?

i totally forgot about #185 tbh, but yea it should've been enough, granted this was a bit more elaborate of ar equest with the different classes and sprites to get an overview but you could close #185 and just keep this one then i guess?

**Comment by ksandin** [comment]
Then it’s the same feature. Closing as duplicate

**Comment by LadyNanuia** [comment]
Yea i suppose you#re right
