### ISSUE TITLE
trying to sync sql dbs and displaying information not working for me.

### ISSUE THREAD

**Issue by sparkro** [ksandin/racp#196]
i spoke with you on reddit about this but i manage to get it all loading however siging in or viewing data on the site is not possible. here are some errors.

```
[1] GET /monster/search/127.0.0.1:8080/settings.readPublic,meta.read,monster.search?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%221%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%222%22%3A%7B%22json%22%3A%7B%22sort%22%3A%5B%7B%22field%22%3A%22WalkSpeed%22%2C%22sort%22%3A%22asc%22%7D%5D%2C%22limit%22%3A18%2C%22filter%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22filter%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D 404 1.137 ms - 9`

`error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@control:/home/racp# nano .env.local
root@control:/home/racp# yarn codegen:rathena
yarn run v1.22.19
$ ts-node --files scripts/generateRAthenaTypes.ts
[file(conf/inter_athena.conf)] read() -> [object Object] in 2ms
Error: ENOENT: no such file or directory, open '/home/racp/scripts/generateRathenaTypes.hbs'
    at Object.openSync (node:fs:603:3)
    at Object.readFileSync (node:fs:471:35)
    at Object.stringifyDatabase (/home/racp/node_modules/@rmp135/sql-ts/dist/DatabaseTasks.js:77:29)
    at Object.<anonymous> (/home/racp/node_modules/@rmp135/sql-ts/dist/index.js:106:57)
    at step (/home/racp/node_modules/@rmp135/sql-ts/dist/index.js:56:23)
    at Object.next (/home/racp/node_modules/@rmp135/sql-ts/dist/index.js:37:53)
    at fulfilled (/home/racp/node_modules/@rmp135/sql-ts/dist/index.js:28:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/racp/scripts/generateRathenaTypes.hbs'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

my env.local file i setup to point to the rathena folder  as instructed. 

````
[0] Starting API with options {
[0]   hostname: '127.0.0.1',
[0]   apiPort: 8082,
[0]   rAthenaPath: '/home/rathena/rathena',
[0]   adminPermissionName: 'channel_admin',
[0]   jwtSecret: 'default',
[0]   exposeInternalErrors: true,
[0]   log: 'verbose',
[0]   tradeScale: 2,
[0]   dataFolder: '/home/racp/data',
[0]   publicFolder: '/home/racp/assets',
[0]   donationEnvironment: 'sandbox',
[0]   preloadResources: false,
[0]   validateResources: false`
```

**Comment by ksandin** [comment]
Hello. It seems you are trying to run `yarn codegen:rathena`. This is a developer command and not something you should use unless you are planning to significantly change the source code of RACP. It is something that is only necessary if upgrading RACP to support new breaking changes coming upstream from rAthena. Also, in that case, it's probably even better to submit a new ticket and ask me to do it.

If you want to run RACP on your local machine in development mode, follow the steps in the development section of the readme:
https://github.com/ksandin/racp#development

If you want to run RACP on your production machine, follow the steps in the deployment section of the readme:
https://github.com/ksandin/racp#deployment

Neither of these sections tell you to run `yarn codegen:rathena`, so you must have misread the readme. Try again and let me know how it went!

**Comment by sparkro** [comment]
I have followed the steps provided in the deployment section the app runs
however when. Visiting the production site I am unable to sign in to an
account or view any data on any of the pages displayed.

**Comment by ksandin** [comment]
The error you posted tells me otherwise. Are you absolutely sure you followed the instructions properly? Have you tried to redoing it from the start to make sure there were no mistakes?

I ask because it should be impossible for you to receive that error if you follow the instructions properly.

**Comment by sparkro** [comment]
I have. If you visit the site I posted you'll notice you are able access
the site no problem I followed everything listed on the deplyment portion
of your documentation. Again ignore the DB stuff I posted I only did that
because I thought it would sync and work

**Comment by ksandin** [comment]
Can you post your `.env.local` contents in this thread? Remove any sensitive details before you do, like your `jwtSecret`.

**Comment by sparkro** [comment]
NODE_ENV=production
reactRefresh=false
hostname=127.0.0.1
apiPort=8082
apiBaseUrl="127.0.0.1:8081"
appPort=8081
rAthenaPath="/home/rathena/rathena/"

so ive tried to put in a few things on hostname a url that points to the server ip and a few other things. but this is what it looks like again pretend hostname is something like control.sparkragnarok.com instead of that or the ip. if i am doing something wrong let me know.

**Comment by ksandin** [comment]
I can spot another error: The value of apiBaseUrl must start with //. This is in the docs :)

**Comment by sparkro** [comment]
i apologize i read this very late at night i just made some changes :) but i still get endless loading...


![image](https://github.com/ksandin/racp/assets/147013365/7dcb9062-0ab5-4402-a29b-e4020d4ae479)

**Comment by ksandin** [comment]
That screenshot doesn't look wrong to me. That's a fairly normal list of files being served.

**Comment by ksandin** [comment]
Also It's 19:30 here, so I'm all right assisting a bit right now.

**Comment by ksandin** [comment]
Yeah I can see the problem. This is definitely related to your reverse proxy and how you're routing traffic on the server.

**Comment by ksandin** [comment]
Your .env configuration seems to be correct now. The problem is that your server is not routing the requests to the api properly. And there I can't really help you, that's just regular server admin responsibilities. RACP seems to be properly installed on your server now.

**Comment by ksandin** [comment]
They also must be routed in your proxy. Opening the ports isn't enough. 

For example, you'll could route like this:
cp.sparkragnarok.com:80 -> localhost:80
cp.sparkragnarok.com:8081 -> localhost:8081

Or you could do:
cp.sparkragnarok.com -> localhost:80
cp-api.sparkragnarok.com -> localhost:8081

This is all up to how you want it to set it up (remember, you'll have to make sure your .env config mirrors these settings)

**Comment by sparkro** [comment]
yeah it seems like cloudpanels way of handling reverse proxy is strange.

**Comment by ksandin** [comment]
> is this related to the api?
> 
> ```
> 2023/10/05 17:17:25 [error] 166803#166803: *2235 connect() failed (111: Connection refused) while connecting to upstream, client: 66.181.119.102, server: cp.sparkragnarok.com, request: "GET /item/search/127.0.0.1:8080/settings.readPublic,meta.read,item.search?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%221%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%222%22%3A%7B%22json%22%3A%7B%22limit%22%3A19%2C%22filter%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22filter%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D HTTP/2.0", upstream: "http://38.45.66.3:8081/item/search/127.0.0.1:8080/settings.readPublic,meta.read,item.search?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%221%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%2C%222%22%3A%7B%22json%22%3A%7B%22limit%22%3A19%2C%22filter%22%3Anull%7D%2C%22meta%22%3A%7B%22values%22%3A%7B%22filter%22%3A%5B%22undefined%22%5D%7D%7D%7D%7D", host: "cp.sparkragnarok.com", referrer: "https://cp.sparkragnarok.com/item/search/eyJsaW1pdCI6MTl9"
> 2023/10/05 17:21:23 [error] 167904#167904: *2444 connect() failed (111: Connection refused) while connecting to upstream, client: 78.82.159.219, server: cp.sparkragnarok.com, request: "GET /127.0.0.1:8080/settings.readPublic?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D HTTP/2.0", upstream: "http://127.0.0.1:8081/127.0.0.1:8080/settings.readPublic?batch=1&input=%7B%220%22%3A%7B%22json%22%3Anull%2C%22meta%22%3A%7B%22values%22%3A%5B%22undefined%22%5D%7D%7D%7D", host: "cp.sparkragnarok.com", referrer: "https://cp.sparkragnarok.com/"
> ```

That's the web server getting invalid requests. That's what it looks like when you have invalid url configurations in your .env config and try to use the website.

**Comment by sparkro** [comment]
i have completely started from scratch as i was unable to get it running. i want to run both a webserver and this hopefully i can get it working here shortly.

**Comment by ksandin** [comment]
Good luck! I'm signing off, but I'll check back in tomorrow. I hope it works out :)

**Comment by sparkro** [comment]
looks like i got it to work well i need to learn to code to build some more functionality into it right now basic create and change password might not be enough for the planned project i have. hoping to integrate some of it to my flarum discussion board once its up and i learn how to do so. appreciate all of the help and hope you continue to add more features.

**Comment by ksandin** [comment]
Np, glad you got it working! There's a bunch of features planned already, so please check out the issue list and give an upvote or comment on any existing issues you'd like to see implemented so I know what I can prioritize.

**Comment by sparkro** [comment]
honestly, i would try to bring some of what fluxcp has for functionality. and it would be golden. i wont be able to use it fully until i can figure out how to run lightspeed+ this with another site but ill follow it
